import {
  ClosePopup,
  Dialog,
  LocalStorage,
  Notify,
  QAvatar,
  QBadge,
  QBtn,
  QBtnToggle,
  QCard,
  QCardActions,
  QCardSection,
  QDialog,
  QHeader,
  QIcon,
  QInput,
  QLayout,
  QPageContainer,
  QSelect,
  QSpace,
  QToggle,
  QToolbar,
  QTooltip,
  Quasar,
} from 'quasar'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(Quasar, {
    components: {
      QAvatar,
      QBadge,
      QBtn,
      QBtnToggle,
      QCard,
      QCardActions,
      QCardSection,
      QDialog,
      QHeader,
      QIcon,
      QInput,
      QLayout,
      QPageContainer,
      QSelect,
      QSpace,
      QToggle,
      QToolbar,
      QTooltip,
    },
    directives: { ClosePopup },
    plugins: { Dialog, LocalStorage, Notify },
    config: {
      brand: { primary: '#d8ff55', secondary: '#f1bd8a', dark: '#17251f' },
    },
  })
})
